version: "3.8"

services:
  mongo:
    image: mongo:4.0.4
    restart: always
    network_mode: bridge
    hostname: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/var/lib/mongo/data


  postgres:
    image: postgres:12.5
    restart: always
    network_mode: bridge
    hostname: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/02.sql
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@QWE123qwe123#

  # backend
  todoapp:
    # Build application by its dockerfile
    build: ./
    container_name: todo-app
    network_mode: bridge
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/test
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/todoapp
      - DB_SERVER=postgres
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@QWE123qwe123#
    ports:
      - 3004:3004
    depends_on:
      - postgres
      - mongo
    links:
      - postgres
      - mongo

# frontend todo
#  todoapp-ui:
#    build: ../frontend/todo-app
#    container_name: todoapp-ui
#    ports:
#      - 8080:8080
#      - 80:8080
#    links:
#      - todoapp

volumes:
  mongodb:
  
  postgresql:
  